export const mockProducts = [
  {
    id: 1,
    name: "T-Shirt",
    brand: "Brand A",
    category: "Tops",
    gender: "Men",
    price: 599,
    color: "Red",
    discount: 10,
    image: "https://via.placeholder.com/150?text=T-Shirt",
    stars: 120,
    likes: 340,
  },
  {
    id: 2,
    name: "Jeans",
    brand: "Brand B",
    category: "Bottoms",
    gender: "Women",
    price: 1299,
    color: "Blue",
    discount: 15,
    image: "https://via.placeholder.com/150?text=Jeans",
    stars: 150,
    likes: 290,
  },
  {
    id: 3,
    name: "Sneakers",
    brand: "Brand C",
    category: "Footwear",
    gender: "Men",
    price: 2999,
    color: "Black",
    discount: 20,
    image: "https://via.placeholder.com/150?text=Sneakers",
    stars: 200,
    likes: 410,
  },
  {
    id: 4,
    name: "Summer Dress",
    brand: "Brand A",
    category: "Dresses",
    gender: "Women",
    price: 2499,
    color: "Pink",
    discount: 5,
    image: "https://via.placeholder.com/150?text=Summer+Dress",
    stars: 100,
    likes: 230,
  },
  {
    id: 5,
    name: "Jacket",
    brand: "Brand B",
    category: "Outerwear",
    gender: "Unisex",
    price: 3499,
    color: "Grey",
    discount: 25,
    image: "https://via.placeholder.com/150?text=Jacket",
    stars: 180,
    likes: 330,
  },
  {
    id: 6,
    name: "Shorts",
    brand: "Brand C",
    category: "Bottoms",
    gender: "Men",
    price: 799,
    color: "Green",
    discount: 10,
    image: "https://via.placeholder.com/150?text=Shorts",
    stars: 90,
    likes: 250,
  },
  {
    id: 7,
    name: "Sweater",
    brand: "Brand A",
    category: "Tops",
    gender: "Women",
    price: 1799,
    color: "Pink",
    discount: 15,
    image: "https://via.placeholder.com/150?text=Sweater",
    stars: 130,
    likes: 280,
  },
  {
    id: 8,
    name: "Cap",
    brand: "Brand B",
    category: "Accessories",
    gender: "Men",
    price: 499,
    color: "Green",
    discount: 5,
    image: "https://via.placeholder.com/150?text=Cap",
    stars: 80,
    likes: 190,
  },
  {
    id: 9,
    name: "Shirt",
    brand: "Brand C",
    category: "Accessories",
    gender: "Men",
    price: 5499,
    color: "Red",
    discount: 20,
    image: "https://via.placeholder.com/150?text=Shirt",
    stars: 250,
    likes: 500,
  },
  {
    id: 10,
    name: "Sunglasses",
    brand: "Brand A",
    category: "Accessories",
    gender: "Women",
    price: 1999,
    color: "Black",
    discount: 10,
    image: "https://via.placeholder.com/150?text=Sunglasses",
    stars: 110,
    likes: 210,
  },
  {
    id: 11,
    name: "Blazer",
    brand: "Brand B",
    category: "Outerwear",
    gender: "Men",
    price: 4999,
    color: "Grey",
    discount: 30,
    image: "https://via.placeholder.com/150?text=Blazer",
    stars: 160,
    likes: 320,
  },
  {
    id: 12,
    name: "Skirt",
    brand: "Brand C",
    category: "Bottoms",
    gender: "Women",
    price: 999,
    color: "Black",
    discount: 20,
    image: "https://via.placeholder.com/150?text=Skirt",
    stars: 140,
    likes: 270,
  },
  {
    id: 13,
    name: "Boots",
    brand: "Brand A",
    category: "Footwear",
    gender: "Unisex",
    price: 3599,
    color: "Brown",
    discount: 15,
    image: "https://via.placeholder.com/150?text=Boots",
    stars: 170,
    likes: 340,
  },
  {
    id: 14,
    name: "Cardigan",
    brand: "Brand B",
    category: "Tops",
    gender: "Women",
    price: 1499,
    color: "Grey",
    discount: 10,
    image: "https://via.placeholder.com/150?text=Cardigan",
    stars: 120,
    likes: 240,
  },
  {
    id: 15,
    name: "Belt",
    brand: "Brand C",
    category: "Accessories",
    gender: "Men",
    price: 799,
    color: "Brown",
    discount: 5,
    image: "https://via.placeholder.com/150?text=Belt",
    stars: 70,
    likes: 150,
  },
];
